project: "run_away_sweep"
name: "v2wsac-sweep-robotics"

method: bayes  
metric:
  name: charts/coverage
  goal: maximize

parameters:
  beta_ratio:
    min: 0.001953125
    max: 0.25
  lr_discriminator:
    min: 0.0001
    max: 0.001
  alpha:
    min: 0.01
    max: 0.2
  nb_episodes_rho:
    values: [2, 4, 8, 16]
  beta_noise:
    min: 0.0
    max: 2.0
  lambda_reward_metra:
    min: 0.0
    max: 1.0
  lambda_wasserstein:
    min: 0.0
    max: 1.0
  seed:
    values: [0, 1, 2, 3, 4]
    

command:
  - proxychains4
  - poetry
  - run
  - python
  - ../v2wsac.py
  - --use_hp_file
  - --sweep_mode
  - --hp_file
  - ../hyper_parameters.json
  - --env_id
  - FetchReach-v1
